services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=prueba
      - POSTGRES_USER=prueba
      - POSTGRES_PASSWORD=123456
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    depends_on:
      - postgres
  
  backend:
    build: ./pruebaBack
    expose:
      - 5000
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
  
  frontend:
    build: ./pruebafront
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres

